THEME_NAME="Catppuccin Mocha"
BG_COLOR="#1e1e2e"
LOCKER_COLOR="1e1e2e"
CLIENT_FOCUSED="#cba6f7   #cba6f7   #1e1e2e   #89dceb   #cba6f7"
CLIENT_FOCUSED_INACTIVE="#45475a   #45475a   #cdd6f4   #313244   #45475a"
CLIENT_UNFOCUSED="#313244   #313244   #585b70   #1e1e2e   #313244"
CLIENT_URGENT="#f38ba8   #f38ba8   #1e1e2e   #f38ba8   #f38ba8"
