THEME_NAME="Nord"
BG_COLOR="#1a1a2e"
LOCKER_COLOR="1a1a2e"
CLIENT_FOCUSED="#5e81ac   #5e81ac   #eceff4   #88c0d0   #5e81ac"
CLIENT_FOCUSED_INACTIVE="#3b4252   #3b4252   #d8dee9   #4c566a   #3b4252"
CLIENT_UNFOCUSED="#2e3440   #2e3440   #4c566a   #3b4252   #2e3440"
CLIENT_URGENT="#bf616a   #bf616a   #eceff4   #bf616a   #bf616a"
