THEME_NAME="Solarized Light"
BG_COLOR="#fdf6e3"
LOCKER_COLOR="fdf6e3"
CLIENT_FOCUSED="#268bd2   #268bd2   #fdf6e3   #2aa198   #268bd2"
CLIENT_FOCUSED_INACTIVE="#93a1a1   #93a1a1   #657b83   #eee8d5   #93a1a1"
CLIENT_UNFOCUSED="#eee8d5   #eee8d5   #93a1a1   #fdf6e3   #eee8d5"
CLIENT_URGENT="#dc322f   #dc322f   #fdf6e3   #dc322f   #dc322f"
